export const state = {
  progress: null,
  activeWorkoutSession: null,
  intervalId: null,
  running: false,
  secondsLeft: 0,
  currentSegmentIndex: 0,
  wakeLockSentinel: null,
  audioCtx: null,
  audioEnabled: true,
  preparedSessionIndex: null,
  dom: {}
};

export function cacheDom() {
  state.dom = {
    body: document.body,
    currentCard: document.getElementById('currentCard'),
    doneCount: document.getElementById('doneCount'),
    remainingCount: document.getElementById('remainingCount'),
    weekCount: document.getElementById('weekCount'),
    resetPlanBtn: document.getElementById('resetPlanBtn'),
    easierModeToggle: document.getElementById('easierModeToggle'),
    dayStateSelect: document.getElementById('dayStateSelect'),
    audioToggle: document.getElementById('audioToggle'),
    exportBtn: document.getElementById('exportBtn'),
    importFileInput: document.getElementById('importFileInput'),
    modeNote: document.getElementById('modeNote'),
    wakelockBadge: document.getElementById('wakelockBadge'),
    plannerTitle: document.getElementById('plannerTitle'),
    planner: document.getElementById('planner'),

    detailsOverlay: document.getElementById('detailsOverlay'),
    detailsTitle: document.getElementById('detailsTitle'),
    detailsMeta: document.getElementById('detailsMeta'),
    detailsStartBtn: document.getElementById('detailsStartBtn'),
    closeDetailsBtn: document.getElementById('closeDetailsBtn'),
    detailsDesign: document.getElementById('detailsDesign'),
    detailsFocus: document.getElementById('detailsFocus'),
    detailsProgression: document.getElementById('detailsProgression'),
    detailsWarmup: document.getElementById('detailsWarmup'),
    detailsExercises: document.getElementById('detailsExercises'),
    detailsCooldown: document.getElementById('detailsCooldown'),
    detailsEasier: document.getElementById('detailsEasier'),
    detailsSubsEnergy: document.getElementById('detailsSubsEnergy'),
    detailsSubsJoint: document.getElementById('detailsSubsJoint'),

    prestartOverlay: document.getElementById('prestartOverlay'),
    prestartTitle: document.getElementById('prestartTitle'),
    prestartMeta: document.getElementById('prestartMeta'),
    closePrestartBtn: document.getElementById('closePrestartBtn'),
    prestartPills: document.getElementById('prestartPills'),
    prestartStats: document.getElementById('prestartStats'),
    prestartSummary: document.getElementById('prestartSummary'),
    prestartFocus: document.getElementById('prestartFocus'),
    prestartAdjustment: document.getElementById('prestartAdjustment'),
    beginWorkoutBtn: document.getElementById('beginWorkoutBtn'),
    prestartDetailsBtn: document.getElementById('prestartDetailsBtn'),
    prestartPreview: document.getElementById('prestartPreview'),

    playerOverlay: document.getElementById('playerOverlay'),
    playerPhaseLabel: document.getElementById('playerPhaseLabel'),
    playerWorkoutTitle: document.getElementById('playerWorkoutTitle'),
    closePlayerBtn: document.getElementById('closePlayerBtn'),
    playerMain: document.getElementById('playerMain'),
    timerText: document.getElementById('timerText'),
    exerciseName: document.getElementById('exerciseName'),
    exerciseCue: document.getElementById('exerciseCue'),
    phaseProgress: document.getElementById('phaseProgress'),
    segmentMeta: document.getElementById('segmentMeta'),
    nextUpBox: document.getElementById('nextUpBox'),
    playerFooterSticky: document.getElementById('playerFooterSticky'),
    playPauseBtn: document.getElementById('playPauseBtn'),
    skipBtn: document.getElementById('skipBtn'),
    completeBtn: document.getElementById('completeBtn'),

    completionBox: document.getElementById('completionBox'),
    completionTitle: document.getElementById('completionTitle'),
    completionText: document.getElementById('completionText'),
    completionNext: document.getElementById('completionNext'),
    closeCompletionBtn: document.getElementById('closeCompletionBtn'),
    repeatSessionBtn: document.getElementById('repeatSessionBtn'),
    completionEasierBtn: document.getElementById('completionEasierBtn')
  };

  return state.dom;
}
